//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.LibraryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Borrow", ReplyAction="http://tempuri.org/IService/BorrowResponse")]
        LibraryApp.LibraryService.BorrowResponse Borrow(LibraryApp.LibraryService.BorrowRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Borrow", ReplyAction="http://tempuri.org/IService/BorrowResponse")]
        System.Threading.Tasks.Task<LibraryApp.LibraryService.BorrowResponse> BorrowAsync(LibraryApp.LibraryService.BorrowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Return", ReplyAction="http://tempuri.org/IService/ReturnResponse")]
        LibraryApp.LibraryService.ReturnResponse Return(LibraryApp.LibraryService.ReturnRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Return", ReplyAction="http://tempuri.org/IService/ReturnResponse")]
        System.Threading.Tasks.Task<LibraryApp.LibraryService.ReturnResponse> ReturnAsync(LibraryApp.LibraryService.ReturnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Renew", ReplyAction="http://tempuri.org/IService/RenewResponse")]
        LibraryApp.LibraryService.RenewResponse Renew(LibraryApp.LibraryService.RenewRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Renew", ReplyAction="http://tempuri.org/IService/RenewResponse")]
        System.Threading.Tasks.Task<LibraryApp.LibraryService.RenewResponse> RenewAsync(LibraryApp.LibraryService.RenewRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Borrow", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BorrowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bookId;
        
        public BorrowRequest() {
        }
        
        public BorrowRequest(string bookId) {
            this.bookId = bookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BorrowResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BorrowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public BorrowResponse() {
        }
        
        public BorrowResponse(string bookId, string message) {
            this.bookId = bookId;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Return", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bookId;
        
        public ReturnRequest() {
        }
        
        public ReturnRequest(string bookId) {
            this.bookId = bookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReturnResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReturnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public ReturnResponse() {
        }
        
        public ReturnResponse(string bookId, string message) {
            this.bookId = bookId;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Renew", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bookId;
        
        public RenewRequest() {
        }
        
        public RenewRequest(string bookId) {
            this.bookId = bookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string bookId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool renewResult;
        
        public RenewResponse() {
        }
        
        public RenewResponse(string bookId, string message, bool renewResult) {
            this.bookId = bookId;
            this.message = message;
            this.renewResult = renewResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : LibraryApp.LibraryService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<LibraryApp.LibraryService.IService>, LibraryApp.LibraryService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryApp.LibraryService.BorrowResponse LibraryApp.LibraryService.IService.Borrow(LibraryApp.LibraryService.BorrowRequest request) {
            return base.Channel.Borrow(request);
        }
        
        public string Borrow(ref string bookId) {
            LibraryApp.LibraryService.BorrowRequest inValue = new LibraryApp.LibraryService.BorrowRequest();
            inValue.bookId = bookId;
            LibraryApp.LibraryService.BorrowResponse retVal = ((LibraryApp.LibraryService.IService)(this)).Borrow(inValue);
            bookId = retVal.bookId;
            return retVal.message;
        }
        
        public System.Threading.Tasks.Task<LibraryApp.LibraryService.BorrowResponse> BorrowAsync(LibraryApp.LibraryService.BorrowRequest request) {
            return base.Channel.BorrowAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryApp.LibraryService.ReturnResponse LibraryApp.LibraryService.IService.Return(LibraryApp.LibraryService.ReturnRequest request) {
            return base.Channel.Return(request);
        }
        
        public string Return(ref string bookId) {
            LibraryApp.LibraryService.ReturnRequest inValue = new LibraryApp.LibraryService.ReturnRequest();
            inValue.bookId = bookId;
            LibraryApp.LibraryService.ReturnResponse retVal = ((LibraryApp.LibraryService.IService)(this)).Return(inValue);
            bookId = retVal.bookId;
            return retVal.message;
        }
        
        public System.Threading.Tasks.Task<LibraryApp.LibraryService.ReturnResponse> ReturnAsync(LibraryApp.LibraryService.ReturnRequest request) {
            return base.Channel.ReturnAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryApp.LibraryService.RenewResponse LibraryApp.LibraryService.IService.Renew(LibraryApp.LibraryService.RenewRequest request) {
            return base.Channel.Renew(request);
        }
        
        public string Renew(ref string bookId, out bool renewResult) {
            LibraryApp.LibraryService.RenewRequest inValue = new LibraryApp.LibraryService.RenewRequest();
            inValue.bookId = bookId;
            LibraryApp.LibraryService.RenewResponse retVal = ((LibraryApp.LibraryService.IService)(this)).Renew(inValue);
            bookId = retVal.bookId;
            renewResult = retVal.renewResult;
            return retVal.message;
        }
        
        public System.Threading.Tasks.Task<LibraryApp.LibraryService.RenewResponse> RenewAsync(LibraryApp.LibraryService.RenewRequest request) {
            return base.Channel.RenewAsync(request);
        }
    }
}
